### ISSUE TITLE
Always UP-TO-DATE after 1st build

### ISSUE THREAD

**Issue by jpenglert** [Ullink/gradle-ikvm-plugin#20]
The ikvm task is always "UP-TO-DATE" after the first run and will never rebuild the assembly when modifying or adding java files. Even if the jar task executes the ikvm task will not. I notice when I delete the debug (*.pdb file) then the ikvm task will run. Something must be misconfigured with the ikvm task inputs. I looked an Ikvm.groovy and didn't see anything glaringly wrong.

**Comment by gluck** [comment]
`project.jar.archivePath` needs to be set as an input of then task, it seems it's not

**Comment by jpenglert** [comment]
I have a fix in progress. Will submit a pull request shortly.
